/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface;

import db.dbClose;
import db.dbConn;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import query.DialogOne;
import query.PreQuery;

/**
 *
 * @author allen
 */
public class NutManagement extends javax.swing.JFrame {
Connection con;
Statement stmt;
PreparedStatement pstmt;
ResultSet rs;
String nutName;
int nutPrice;
int nutNumber;
  String sql;



    /**
     * Creates new form NutManagement
     */
    public NutManagement() {
        initComponents(); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        NutName = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        NutPrice = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        HowManyExist = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("名称");

        jLabel2.setText("价格");

        jLabel3.setText("存货量");

        jButton1.setText("添加货物");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("更新货物");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("删除货物");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("查询货物");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton4)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton2))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(48, 48, 48)
                                .addComponent(NutName, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(NutPrice, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                                    .addComponent(HowManyExist))))
                        .addGap(31, 31, 31)
                        .addComponent(jButton3)))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NutName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(NutPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(HowManyExist, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addGap(18, 18, 18)
                .addComponent(jButton4)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    try {
        con=dbConn.getConn("Nut");
      sql="insert into Nut values(?,?,?)";
      pstmt=con.prepareStatement(sql);
      this.nutName = NutName.getText().trim();
       nutPrice=Integer.parseInt(NutPrice.getText().trim());
       nutNumber=Integer.parseInt(HowManyExist.getText().trim());
      pstmt.setString(1, nutName);
      pstmt.setInt(2, nutPrice);
      pstmt.setInt(3, nutNumber);
      if(pstmt.executeUpdate()>0)
      JOptionPane.showMessageDialog(null, "添加商品成功！");
     else
          JOptionPane.showMessageDialog(null,"添加商品失败！","警告",JOptionPane.ERROR_MESSAGE);
        
// TODO add your handling code here:
    } catch (SQLException ex) {
        Logger.getLogger(NutManagement.class.getName()).log(Level.SEVERE, null, ex);
    }finally{dbClose.addClose(con, pstmt);}
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    try {
        nutName = NutName.getText().trim();
        sql="update Nut set price=?,number=? where name='"+nutName+"'";
        nutPrice=Integer.parseInt(NutPrice.getText().trim());
       nutNumber=Integer.parseInt(HowManyExist.getText().trim());
       pstmt=dbConn.getPreparedState("Nut", sql);
        pstmt.setInt(1, nutPrice);
        pstmt.setInt(2,nutNumber);
        if(pstmt.executeUpdate()>0)
            JOptionPane.showMessageDialog(null, "更新商品成功！");
        else
            JOptionPane.showMessageDialog(null,"更新商品失败！","警告",JOptionPane.ERROR_MESSAGE);
        // TODO add your handling code here:
    } catch (SQLException ex) {
        Logger.getLogger(NutManagement.class.getName()).log(Level.SEVERE, null, ex);
    }finally{dbClose.addClose(con, pstmt);}
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        sql="select * from Nut where name='"+nutName+"'";
        PreQuery query = null;
        query.setDatabaseName("Nut");
        query.setSQL(sql);
        query.startQuery();
        DialogOne dialog = null;
        dialog.setZiduan(query.getColumnName());
        dialog.setRecord(query.getRecord());
        dialog.init();
        dialog.setVisible(true);
        nutName=NutName.getText().trim();
        dbClose.addClose(con, pstmt);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
    try {
        sql="delete from Nut where name='"+nutName+"'";
        pstmt=dbConn.getPreparedState("Nut", sql);
        nutName=NutName.getText().trim();     
if(pstmt.executeUpdate()>0)
JOptionPane.showMessageDialog(null,"删除试题成功");
else JOptionPane.showMessageDialog(null,"删除试题失败","警告",JOptionPane.ERROR_MESSAGE);
// TODO add your handling code here:
    } catch (SQLException ex) {
        Logger.getLogger(NutManagement.class.getName()).log(Level.SEVERE, null, ex);
    }finally{dbClose.addClose(con, pstmt);}
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField HowManyExist;
    private javax.swing.JTextField NutName;
    private javax.swing.JTextField NutPrice;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
